Added additional preview cards with box cards.
Kamalisk/arkhamdb-json-data pull request #1022
Opened 2021-08-31 21:04 UTC by clayton-grey

Includes: Protecting the Arnirniq, Foresight, "Hit Me!", Gené Beauregard, Meditative Trance, Fire Extinguisher

2021-09-06 14:49 UTC, robert-huang requested changes

2021-09-06 14:49 UTC, robert-huang commented on pack/eoe/eoep.json
> +        "subtype_code": "weakness",
small mistake here, remove this line please

2021-09-06 14:49 UTC, robert-huang commented on pack/eoe/eoep.json
> +        "traits": "Inisght. Spirit.",
typo Insight

2021-09-06 14:49 UTC, robert-huang commented on pack/eoe/eoep.json
> +        "text": "[action]: <b>Fight.</b> You get +1 [combat] and deal +1 damage for this attack.\n[action] Discard Fire Extinguisher: <b>Evade.</b> Automatically evade all enemies engaged with you. Y
I believe we use [[Elite]] instead (and for anything that is a Trait in the card text)

2021-09-06 14:49 UTC, robert-huang commented on pack/eoe/eoep.json
> +        "cost": 2,
cost 5

2021-09-06 14:49 UTC, robert-huang commented on pack/eoe/eoep.json
> +        "illustrator": "Vlad Ricean",
I don't believe we know for sure who the illustrator is right? Best I can find for this card is https://i.imgur.com/4vK8jyl_d.webp?maxwidth=760&fidelity=grand (and the unsanctioned spoiler has a camera flash hiding the illustrator name hahah)

2021-09-06 14:49 UTC, robert-huang commented on pack/eoe/eoep.json
> +        "text": "Fast. Play after an <b><i>Ally</i></b> asset at your location is discarded by a card effect or is defeated.\nEither return that asset to its owner's hand, or its owner draws 3 cards.
[[Ally]]

2021-09-06 14:52 UTC, drawntotheflame commented on pack/eoe/eoep.json
> +        "text": "Permanent. Limit 1 per deck. Purchase at deck creation.\n<b>Forced</b> - When your first turn of the game begins: Play any number of <b><i>Item</i></b> assets from your hand, reducin
NB [[]] for traits in game text, not bold and ital tags.

2021-09-09 15:03 UTC, drawntotheflame commented
@Kamalisk this can go live - thanks

2021-09-12 19:20 UTC, merged