Add Twisted Hollow Encounter Cards
Kamalisk/arkhamdb-json-data pull request #1432
Opened 2024-10-20 16:59 UTC by adamgfraser

2024-10-21 15:42 UTC, drawntotheflame reviewed
Good job! Great, very thorough, only a few tweaks. 

The big thing was the inversion of front/back locations - but I've made suggestions to amend that, and hopefully it won't be too tricky for you to work through that. Thank you.

2024-10-21 15:42 UTC, drawntotheflame commented on pack/fhv/fhvc.json
> +    "back_flavor": "The winding paths loop back on themselves.",
```suggestion
    "back_flavor": "The trees grew too thickly, and their trunks were too big for any healthy New England wood. There was too much silence in the dim alleys between them, and the floor was too soft with the dank moss and mattings of infinite years of decay.\n - H. P. Lovecraft, \"The Colour Out of Space\"",
```

2024-10-21 15:42 UTC, drawntotheflame commented on pack/fhv/fhvc.json
> +    "back_illustrator": "Walter Brocca",
Please delete this line.

2024-10-21 15:42 UTC, drawntotheflame commented on pack/fhv/fhvc.json
> +    "name": "Western Woods",
```suggestion
    "name": "Crooked Path",
```

2024-10-21 15:42 UTC, drawntotheflame commented on pack/fhv/fhvc.json
> +    "back_illustrator": "Lin Hsiang",
```suggestion
    "back_illustrator": "Walter Brocca",
```

2024-10-21 15:42 UTC, drawntotheflame commented on pack/fhv/fhvc.json
> +    "back_illustrator": "Lin Hsiang",
Please add:

`"back_flavor": "The trees grew too thickly, and their trunks were too big for any healthy New England wood. There was too much silence in the dim alleys between them, and the floor was too soft with the dank moss and mattings of infinite years of decay.\n - H. P. Lovecraft, \"The Colour Out of Space\"",`

2024-10-21 15:42 UTC, drawntotheflame commented on pack/fhv/fhvc.json
> +    "back_traits": "Forest. Lair. Dark.",
```suggestion
    "back_traits": "Forest. Dark.",
```

2024-10-21 15:42 UTC, drawntotheflame commented on pack/fhv/fhvc.json
> +    "flavor": "The trees grew too thickly, and their trunks were too big for any healthy New England wood. There was too much silence in the dim alleys between them, and the floor was too soft with t
Please delete this line.

2024-10-21 15:42 UTC, drawntotheflame commented on pack/fhv/fhvc.json
> +    "illustrator": "Walter Brocca",
```suggestion
    "illustrator": "Lin Hsiang",
```

2024-10-21 15:42 UTC, drawntotheflame commented on pack/fhv/fhvc.json
> +    "traits": "Forest. Dark.",
```suggestion
    "traits": "Forest. Lair. Dark.",
```

2024-10-21 15:42 UTC, drawntotheflame commented on pack/fhv/fhvc.json
> +    "back_name": "Bear Den",
```suggestion
    "back_name": "Western Woods",
```

2024-10-21 15:42 UTC, drawntotheflame commented on pack/fhv/fhvc.json
> +    "back_illustrator": "Walter Brocca",
Please delete this line.

2024-10-21 15:42 UTC, drawntotheflame commented on pack/fhv/fhvc.json
> +    "back_name": "The Twisted Hollow",
```suggestion
    "back_name": "Western Woods",
```

2024-10-21 15:42 UTC, drawntotheflame commented on pack/fhv/fhvc.json
> +    "name": "Western Woods",
```suggestion
    "name": "The Twisted Hollow",
```

2024-10-21 15:42 UTC, drawntotheflame commented on pack/fhv/fhvc.json
> +    "test": "<b>Revelation - Test [willpower] (3). This test gets +2 difficulty if your location is [[Dark]]. If you fail, you must either (choose one):\n- Take 2 horror.\n- The investigator who cont
```suggestion
    "test": "<b>Revelation - Test [willpower] (3). This test gets +2 difficulty if your location is [[Dark]]. If you fail, you must either <i>(choose one)</i>:\n- Take 2 horror.\n- The investigator who controls the Vale Lantern flips it to its [[Unlit]] side and places it at a connecting location.",
```

2024-10-21 15:42 UTC, drawntotheflame commented on pack/fhv/fhvc.json
> +    "text": "Peril.\n<b>Revelation</b> - You must either (choose one):\n- Place 1 doom on the current agenda. This effect can cause the agenda to advance.\n- Flip the Vale Lantern to its [[Unlit]] si
```suggestion
    "text": "Peril.\n<b>Revelation</b> - You must either <i>(choose one)</i>:\n- Place 1 doom on the current agenda. This effect can cause the agenda to advance.\n- Flip the Vale Lantern to its [[Unlit]] side. Place the Vale Lantern at the empty location farthest from all investigators.",
```

2024-10-27 01:26 UTC, adamgfraser commented
@drawntotheflame Updated now!

2024-11-03 11:04 UTC, drawntotheflame commented
@Kamalisk this can go live once #1382 is up. Thanks.

2024-11-17 09:02 UTC, fspoettel requested changes

2024-11-17 09:02 UTC, fspoettel commented on pack/fhv/fhvc.json
> +    "text": "<b>Forced</b> - After a location is revealed: Put locations from the top of the Woods deck into play above, below, to the left, and to the right of that location.\n<b>Forced<\b> - When t
```suggestion
    "text": "<b>Forced</b> - After a location is revealed: Put locations from the top of the Woods deck into play above, below, to the left, and to the right of that location.\n<b>Forced</b> - When the investigation phase ends: Each investigator at a [Dark]] location must either draw an enemy in pursuit with the highest evade or take 1 horror (cannot be canceled).",
```

2024-11-17 09:02 UTC, fspoettel commented on pack/fhv/fhvc.json
> +    "text": "Fecund Thicket gets -X shroud, where X is the current darkness level.\n<b>Forced<\b> - After you reveal Fecund Thicket: Test [agility] (X), where X is the current darkness level. If you
```suggestion
    "text": "Fecund Thicket gets -X shroud, where X is the current darkness level.\n<b>Forced</b> - After you reveal Fecund Thicket: Test [agility] (X), where X is the current darkness level. If you fail, find the enemy in pursuit with the highest printed health and spawn it at this location.",
```

2024-11-17 09:02 UTC, fspoettel commented on pack/fhv/fhvc.json
> +    "text": "While an enemy is moving, its location is considered to be connected to Moonlit Clearing.\n<b>Forced<\b> - After you reveal Moonlit Clearing: Test [willpower] (X), where X is the current
```suggestion
    "text": "While an enemy is moving, its location is considered to be connected to Moonlit Clearing.\n<b>Forced</b> - After you reveal Moonlit Clearing: Test [willpower] (X), where X is the current darkness level. If you fail, find the enemy in pursuit with the highest fight and spawn it at this location.",
```

2024-11-17 09:02 UTC, fspoettel commented on pack/fhv/fhvc.json
> +    "name": "Western Woods",
```suggestion
    "name": "Corpse Grove",
```

2024-12-08 18:21 UTC, merged