Update blbe_encounter.json
Kamalisk/arkhamdb-json-data pull request #1438
Opened 2024-11-01 00:49 UTC by somethingtemporaryarkham

Added the rest of the Blob That Ate Everything Else encounter cards.

2024-11-01 00:50 UTC, somethingtemporaryarkham commented
@fspoettel @drawntotheflame Pinging for review of the Blob That Ate Everything Else encounter cards that I added.

2024-12-08 10:51 UTC, drawntotheflame reviewed
Great job, @somethingtemporaryarkham - I think you did a really thorough effort on the story cards and all the changing details on the aberrations.
I've suggested some tidy-ups, mainly with spacing or formatting, and a few times where the code/encounter position/position needed correcting, but otherwise, terrific work!  Thank you.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "code": "89001",
Suzi and her cards are 89001 to 89005, so please can this change? 

```suggestion
    "code": "89006",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "code": "89001",
I'll mark the changes so that the code matches the card number throughout.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
No need for a line space between card entries - please delete.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "code": "89002",
```suggestion
    "code": "89007",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_position": 6,
```suggestion
    "encounter_position": 1,
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_position": 7,
```suggestion
    "encounter_position": 2,
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
```suggestion
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
Please delete line.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "code": "89003",
```suggestion
    "code": "89008",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_position": 8,
```suggestion
    "encounter_position": 3,
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "position": 3,
```suggestion
    "position": 8,
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
Please delete.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "code": "89004",
```suggestion
    "code": "89009",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_position": 9,
```suggestion
    "encounter_position": 4,
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "position": 4,
```suggestion
    "position": 9,
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "illustrator": "Ethan Patrik Harris",
```suggestion
    "illustrator": "Ethan Patrick Harris",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
Please delete.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "code": "89008",
```suggestion
    "code": "89010d",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "illustrator": "Ethan Patrik Harris",
```suggestion
    "illustrator": "Ethan Patrick Harris",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
Please delete.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "code": "89009",
```suggestion
    "code": "89010e",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "illustrator": "Ethan Patrik Harris",
```suggestion
    "illustrator": "Ethan Patrick Harris",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
Please delete.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "code": "89010",
```suggestion
    "code": "89010f",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "illustrator": "Ethan Patrik Harris",
```suggestion
    "illustrator": "Ethan Patrick Harris",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "text": "<b>Replicate</b> - After you spot an asset being defeated by an Ooze enemy’s attack, discard that enemy and spawn this enemy exhausted in its place (unless the investigators spend a coun
```suggestion
    "text": "<b>Replicate</b> - After you spot an asset being defeated by an [[Ooze]] enemy’s attack, discard that enemy and spawn this enemy exhausted in its place (unless the investigators spend a countermeasure).\nHunter.\n<b>Forced</b> - When Replicating Aberration leaves play: Return it to the event organizer.\n<b>Blob 3.</b>",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
Please delete.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "code": "89011",
```suggestion
    "code": "89010g",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "illustrator": "Ethan Patrik Harris",
```suggestion
    "illustrator": "Ethan Patrick Harris",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
Please delete.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "code": "89012",
```suggestion
    "code": "89010i",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "illustrator": "Ethan Patrik Harris",
```suggestion
    "illustrator": "Ethan Patrick Harris",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
Please delete.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "code": "89013",
```suggestion
    "code": "89010j",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "illustrator": "Ethan Patrik Harris",
```suggestion
    "illustrator": "Ethan Patrick Harris",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
Please delete.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
Please delete.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
Please delete.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "sanity": null,
For some reason historically for blank health/sanity values we've simply skipped the line, but putting null in here should be fine too.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
Please delete.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "back_text": "<b>Read only if \"the brain was taken:\"</b>\nRemove Mi-Go Scientist, Brain Case, and this card from the game. The investigators, as a group, return 3 of their clues to the token po
```suggestion
    "back_text": "<b>Read only if \"the brain was taken:\"</b>\nRemove Mi-Go Scientist, Brain Case, and this card from the game. The investigators, as a group, return 3 of their clues to the token pool.\n<hr><b>Read only if \"the brain was recovered:\"</b>\n<blockquote><i>The scientists listen to your story and examine the cylinder. To your surprise, you hear a distorted voice from what must be a strange speaker stemming from the jar. The brain vibrates within. \"Oh, thank the heavens. I can hear you. Where am I?\" it asks. You explain what has transpired, and ask why the creatures were after it. \"I know something they needed. Here, I can teach you - do you have a pen?\"</i></blockquote>\nPut the set-aside Corrosive Cloud story asset into play under any investigator’s control. Remove Brain Case from the game. Add Mi-Go Scientist and this card to the victory display. Any investigator discovers 1 clue each from up to 2 locations. Gain 1 countermeasure.",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "flavor": "You thought you’d seen everything, but when you spot one of the creatures flying overhead with a human brain in its grasp, you realize you’re sorely mistaken. Even more surprising, it
```suggestion
    "flavor": "You thought you’d seen everything, but when you spot one of the creatures flying overhead with a human brain in its grasp, you realize you’re sorely mistaken. Even more surprising, it seemed to be cradling the brain safely inside a glass cylinder, as if it were a scientific sample. Are these monsters collecting human brains? The irony isn’t lost on you - the creatures are likely doing the same kind of research as the scientists at the research site - but even still, you have to find this creature and stop this sick experiment!",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "position": 17,
```suggestion
    "position": 14,
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
Please delete.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
Please delete.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
Please delete.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "back_text": "<b>Read only if \"the Mi-Go completed their research:\"</b>\nRemove both Mi-Go Researchers and this card from the game. Each [[Ooze]] enemy that was researched readies and heals all
```suggestion
    "back_text": "<b>Read only if \"the Mi-Go completed their research:\"</b>\nRemove both Mi-Go Researchers and this card from the game. Each [[Ooze]] enemy that was researched readies and heals all damage on it. An investigator returns 1 of their clues to the token pool.\n<hr><b>Read only if \"the Mi-Go research was stopped:\"</b>\n<blockquote><i>Eventually, the creatures’ thirst for knowledge isn’t enough to keep them in this hostile environment, and they flee back to the void of space - at least, for now. In the aftermath, you recover one of the strange tools the creatures were carrying: a scalpel of some glasslike, razor-sharp material.</i></blockquote>\nPut the set-aside Alien Instruments story asset into play under any investigator’s control. Add both Mi‑Go Researchers and this card to the victory display. Until the end of the game, each [[Mi-Go]] enemy gets –2 health and –2 evade. Any investigator discovers 1 clue at any revealed location.",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
Please delete.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "code": "89017",
```suggestion
    "code": "89018",
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_position": 9,
```suggestion
    "encounter_position": 8,
```

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_position": 9,
We go with the lower number for encounter position if given a choice.

2024-12-08 10:51 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +
Please delete.

2024-12-08 11:13 UTC, fspoettel requested changes

2024-12-08 11:13 UTC, fspoettel commented on pack/side/blbe_encounter.json
> +    "encounter_code": "blbe",
This encounter code does not exist, so the set cannot be imported into the database. There is an existing set `blob_that_ate_everything_else` that we can use here.

2024-12-08 13:23 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_code": "blbe",
```suggestion
    "encounter_code": "blob_that_ate_everything_else",
```

2024-12-08 13:23 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_code": "blbe",
```suggestion
    "encounter_code": "blob_that_ate_everything_else",
```

2024-12-08 13:23 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_code": "blbe",
```suggestion
    "encounter_code": "blob_that_ate_everything_else",
```

2024-12-08 13:23 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_code": "blbe",
```suggestion
    "encounter_code": "blob_that_ate_everything_else",
```

2024-12-08 13:23 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_code": "blbe",
```suggestion
    "encounter_code": "blob_that_ate_everything_else",
```

2024-12-08 13:23 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_code": "blbe",
```suggestion
    "encounter_code": "blob_that_ate_everything_else",
```

2024-12-08 13:23 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_code": "blbe",
```suggestion
    "encounter_code": "blob_that_ate_everything_else",
```

2024-12-08 13:23 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_code": "blbe",
```suggestion
    "encounter_code": "blob_that_ate_everything_else",
```

2024-12-08 13:23 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_code": "blbe",
```suggestion
    "encounter_code": "blob_that_ate_everything_else",
```

2024-12-08 13:23 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_code": "blbe",
```suggestion
    "encounter_code": "blob_that_ate_everything_else",
```

2024-12-08 13:23 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_code": "blbe",
```suggestion
    "encounter_code": "blob_that_ate_everything_else",
```

2024-12-08 13:23 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_code": "blbe",
```suggestion
    "encounter_code": "blob_that_ate_everything_else",
```

2024-12-08 13:23 UTC, drawntotheflame commented on pack/side/blbe_encounter.json
> +    "encounter_code": "blbe",
```suggestion
    "encounter_code": "blob_that_ate_everything_else",
```

2024-12-08 21:52 UTC, somethingtemporaryarkham commented
@fspoettel @drawntotheflame Thanks for the formatting comments; I accepted the changes and removed the lines between the different cards. Let me know if there's anything else!

2024-12-13 20:21 UTC, fspoettel reviewed
@somethingtemporaryarkham one more thing I noticed

2024-12-13 20:21 UTC, fspoettel commented on pack/side/blbe_encounter.json
> +    "code": "89010j",
```suggestion
    "code": "89010i",
```

2024-12-13 20:21 UTC, fspoettel commented on pack/side/blbe_encounter.json
> +    "code": "89010i",
```suggestion
    "code": "89010h",
```

2025-01-07 15:29 UTC, somethingtemporaryarkham commented
@fspoettel Done!

2025-01-09 14:10 UTC, merged