Starte Investigator decks Spanish translation
Kamalisk/arkhamdb-json-data pull request #748
Opened 2020-09-03 13:05 UTC by fafranco82

2020-09-11 14:19 UTC, javiSBP requested changes
Enhorabuena por el currazo!! he visto estos errores. Supongo que Jacqueline y Harvey irán en otra PR ¿no?

2020-09-11 14:19 UTC, javiSBP commented on translations/es/pack/investigator/nat.json
> +        "text": "Rápido. Juega esta carta durante cualquier oportunidad [free].\n<b>Enfrentarse.</b> <b>Combatir.</b> Elige un Enemigo que no sea [[Élite]] y que esté a un máximo de 2 Lugares de dist
`[[Élite]]` sin acento

2020-09-11 14:19 UTC, javiSBP commented on translations/es/pack/investigator/win.json
> +        "text": "<b>Evitar.</b> Añade tu [intellect] a tu valor de habilidad para este intento de evitar. Si tienes éxito por 1 o más y el Enemigo no es [[Élite]], no se prepara durante la siguiente
[[Élite]] sin acento

2020-09-15 08:40 UTC, Muadiv commented on translations/es/pack/investigator/ste.json
> +        "back_flavor": "Antes de que Stella empezara a trabajar en el servicio postal de Arkham, había dos cosas que sabía con certeza: la primera, que sus padres habían cometido un error al consider
nombre , en lugar de nomvre

2020-09-15 10:41 UTC, fafranco82 commented on translations/es/pack/investigator/nat.json
> +        "text": "Rápido. Juega esta carta durante cualquier oportunidad [free].\n<b>Enfrentarse.</b> <b>Combatir.</b> Elige un Enemigo que no sea [[Élite]] y que esté a un máximo de 2 Lugares de dist
![image](https://user-images.githubusercontent.com/5708531/93200838-a1aaef80-f750-11ea-88e3-4aab7bcc8ffe.png)

es **Élite**, no **Elite**. Esta si estaba bien ;)

2020-09-15 10:56 UTC, javiSBP requested changes

2020-09-15 10:56 UTC, javiSBP commented on translations/es/pack/investigator/nat.json
> +        "flavor": "\"Tienes que de hacer esto, Nathaniel. Te acabarán matando antes o después.\"",
`Tienes que dejar de hacer esto` falta el "jar" de "dejar" 😃

2020-09-15 11:00 UTC, fafranco82 commented on translations/es/pack/investigator/nat.json
> +        "flavor": "\"Tienes que de hacer esto, Nathaniel. Te acabarán matando antes o después.\"",
Realmente faltaba un `dejar` entero U_U

2020-09-20 21:52 UTC, javiSBP approved these changes
LGTM

2020-09-25 19:43 UTC, TengounPlan commented
El archivo translations/es/encounters.json lo actualizamos/corregimos hace un par de semanas. No nos dimos cuenta de que estaba incluido en este PR, disculpad.

2020-09-26 14:34 UTC, javiSBP commented
> El archivo translations/es/encounters.json lo actualizamos/corregimos hace un par de semanas. No nos dimos cuenta de que estaba incluido en este PR, disculpad.

No creo que sea mayor problema, gracias por el trabajazo que estáis haciendo con ArkhamDB y la app Arkham Cards.

@fafranco82 necesitas ayuda para resolver los conflictos? A ver si así la mergean  y podemos tener los mazos de inicio traducidos 😃

2020-09-26 14:40 UTC, fafranco82 commented
me temo que no soy yo quien los tienes que resolver, sino quien integre finalmente el PR en la rama....

de todas formas existe un "truco" para evitar tantos conflictos, que tomar los archivos cambiados en este PR (que por fortuna están todos dentro de la misma carpeta y no afecta al resto de idiomas o la parte principal), copiarlos en otro lado, descartar el PR, volver a hacer una rama sacada directamente del `master` y crear de nuevo el PR.

2020-09-26 15:06 UTC, javiSBP commented
Hay otra forma, hacer un merge commit de la rama master actualizada sobre tu rama y que en ese merge commit vayan resueltos los conflictos.

2020-09-26 16:18 UTC, fafranco82 commented
¡Hecho!

2020-09-26 16:26 UTC, javiSBP commented
Grande!!!! 🙌

2020-09-26 16:27 UTC, javiSBP approved these changes
Por si acaso LGTM

2020-09-28 23:25 UTC, merged